# Generated by Django 2.0.2 on 2018-04-21 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(default='', max_length=5000)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_members', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='HackRateByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=1000)),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Invintation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='unknown_img.jpg', upload_to='uploads/')),
                ('access_level', models.IntegerField(default=0, verbose_name='Уровень доступа')),
                ('birthday', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('vk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='[Undefinded]', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hackathones', models.ManyToManyField(to='server.Hackathon')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.FloatField()),
                ('backend', models.FloatField()),
                ('ml', models.FloatField()),
                ('management', models.FloatField()),
                ('design', models.FloatField()),
                ('ar', models.FloatField()),
                ('blockchain', models.FloatField()),
                ('android', models.FloatField()),
                ('ios', models.FloatField()),
                ('d2', models.FloatField()),
                ('d3', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='server.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invintation',
            name='from_Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_Profile', to='server.Profile'),
        ),
        migrations.AddField(
            model_name='invintation',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon', to='server.Hackathon'),
        ),
        migrations.AddField(
            model_name='invintation',
            name='to_Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_Profile', to='server.Profile'),
        ),
        migrations.AddField(
            model_name='hackratebyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Profile'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='server.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ManyToManyField(to='server.Profile'),
        ),
    ]
