# Generated by Django 2.0.2 on 2018-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='android',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='ar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='backend',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='blockchain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='d2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='d3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='frontend',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='ios',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='management',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='ml',
            field=models.FloatField(default=0),
        ),
    ]
