# Generated by Django 2.0.2 on 2018-04-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invintation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(default=0, verbose_name='Уровень доступа')),
                ('birthday', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100, verbose_name='GITHUB')),
                ('facebook', models.CharField(max_length=100, verbose_name='FACEBOOK')),
                ('vk', models.CharField(max_length=100, verbose_name='VK')),
                ('skills', models.ManyToManyField(to='server.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='invintation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='server.User'),
        ),
        migrations.AddField(
            model_name='invintation',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon', to='server.Hackathon'),
        ),
        migrations.AddField(
            model_name='invintation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='server.User'),
        ),
    ]
