# Generated by Django 2.0.2 on 2018-04-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(default=0, verbose_name='Уровень доступа')),
                ('birthday', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100, verbose_name='GITHUB')),
                ('facebook', models.CharField(max_length=100, verbose_name='FACEBOOK')),
                ('vk', models.CharField(max_length=100, verbose_name='VK')),
                ('skills', models.ManyToManyField(to='server.Skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='invintation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='invintation',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invintation',
            name='from_Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_Profile', to='server.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invintation',
            name='to_Profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_Profile', to='server.Profile'),
            preserve_default=False,
        ),


    ]
