# Generated by Django 2.0.4 on 2018-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180420_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_members',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
