# Generated by Django 2.0.2 on 2018-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180420_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.CharField(default=12, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(default=2, max_length=2000),
            preserve_default=False,
        ),
    ]
