# Generated by Django 2.0.4 on 2018-04-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180420_2240'),
        ('server', '0003_auto_20180420_2211'),
    ]

    operations = [
    ]
