# Generated by Django 2.0.2 on 2018-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180421_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='server.Tag', verbose_name='Теги'),
        ),
    ]
