# Generated by Django 2.0.4 on 2018-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20180421_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('info', models.CharField(max_length=1000)),
                ('user', models.ManyToManyField(to='server.Profile')),
            ],
        ),
    ]
