# Generated by Django 2.0.2 on 2018-04-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0010_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.FloatField()),
                ('backend', models.FloatField()),
                ('ml', models.FloatField()),
                ('management', models.FloatField()),
                ('design', models.FloatField()),
                ('ar', models.FloatField()),
                ('blockchain', models.FloatField()),
                ('android', models.FloatField()),
                ('ios', models.FloatField()),
                ('d2', models.FloatField()),
                ('d3', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
