# Generated by Django 2.0.2 on 2018-04-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.Profile'),
        ),
    ]
