# Generated by Django 2.0.4 on 2018-04-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_hackratebyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackratebyuser',
            name='hack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hackathon'),
        ),
        migrations.AlterField(
            model_name='hackratebyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Profile'),
        ),
    ]
