# Generated by Django 2.0.4 on 2018-04-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20180421_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackratebyuser',
            name='hack',
        ),
        migrations.AddField(
            model_name='hackratebyuser',
            name='hack',
            field=models.ManyToManyField(to='server.Hackathon'),
        ),
        migrations.RemoveField(
            model_name='hackratebyuser',
            name='user',
        ),
        migrations.AddField(
            model_name='hackratebyuser',
            name='user',
            field=models.ManyToManyField(to='server.Profile'),
        ),
    ]
