# Generated by Django 2.0.4 on 2018-04-21 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20180421_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackRateByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=1000)),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Profile')),
            ],
        ),
    ]
