# Generated by Django 2.0.2 on 2018-04-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20180421_1351'),
        ('server', '0017_hackratebyuser'),
    ]

    operations = [
    ]
