# Generated by Django 2.0.4 on 2018-04-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_merge_20180421_1517'),
        ('server', '0018_merge_20180421_1427'),
    ]

    operations = [
    ]
